version: '3.8'

services:
  themovie_backend:
    build: .
    container_name: themovie_container
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    ports:
      - 5433:5433
    container_name: postgresql_container
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - C:\Users\Acer\Desktop\ITSTEAP\software development\Курсовой проект WEB-программирование\postgresql-data:/var/lib/postgresql/data
    restart: always
